/**
 * Regenerates `packages/react/src/styles/theme.css` (docs/11 section 4, docs/06 section 2).
 *
 * Not part of `build`: it downloads and runs the shadcn CLI, and the palette only moves when
 * shadcn's default theme does. Run it by hand, read the diff, commit the result:
 *
 *   pnpm --filter @docs/react gen:theme
 *
 * It copies the `:root` and `.dark` variable blocks out of a fresh init and rewrites the
 * selectors to `.docs-root` and `.dark .docs-root, .dark.docs-root`, so the theme paints the
 * module and nothing else - the host's own `--background` is never touched (D-11).
 */
import { execFileSync } from 'node:child_process';
import { mkdtemp, readFile, readdir, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, sep } from 'node:path';
import { fileURLToPath } from 'node:url';

const OUT = fileURLToPath(new URL('../packages/react/src/styles/theme.css', import.meta.url));
// `-n` and `--no-monorepo` answer the two prompts init would otherwise block on.
const INIT = [
  '--yes',
  'shadcn@latest',
  'init',
  '-b',
  'radix',
  '-t',
  'vite',
  '-p',
  'nova',
  '-n',
  'theme',
  '--no-monorepo',
  '-y',
];

/** The declarations inside `<selector> { ... }`, brace matched so a nested block cannot cut it short. */
function block(css: string, selector: string): string {
  const start = css.indexOf(`${selector} {`);
  if (start === -1) throw new Error(`gen-theme: the shadcn output has no ${selector} block`);
  let depth = 0;
  for (let i = css.indexOf('{', start); i < css.length; i++) {
    if (css[i] === '{') depth++;
    else if (css[i] === '}' && --depth === 0) return css.slice(css.indexOf('{', start) + 1, i);
  }
  throw new Error(`gen-theme: unterminated ${selector} block`);
}

const indent = (body: string): string =>
  body
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .map((line) => `  ${line}`)
    .join('\n');

const dir = await mkdtemp(join(tmpdir(), 'docs-theme-'));
console.log(`gen-theme: npx ${INIT.join(' ')} in ${dir}`);
execFileSync('npx', INIT, { cwd: dir, stdio: 'inherit' });

// The template decides the file name, so find it by content rather than by path.
const files = (await readdir(dir, { recursive: true })).filter(
  (path) => path.endsWith('.css') && !path.split(sep).includes('node_modules'),
);
let source: string | undefined;
for (const path of files) {
  const text = await readFile(join(dir, path), 'utf8');
  if (text.includes('--sidebar-ring:')) {
    source = text;
    console.log(`gen-theme: reading ${path}`);
    break;
  }
}
if (source === undefined) throw new Error(`gen-theme: no theme css under ${dir}`);

await writeFile(
  OUT,
  `/**
 * Optional theme (D-11, docs/06 section 2): shadcn's default neutral palette, scoped to
 * \`.docs-root\` so importing it can never repaint the host. A host with its own shadcn
 * variables skips this file and the module reads theirs.
 *
 * Generated by \`scripts/gen-theme.ts\` from \`npx shadcn@latest init -b radix\`
 * (style radix-nova, base color neutral). Edit the script, not this file.
 */
.docs-root {
${indent(block(source, ':root'))}
}

/* Both forms: the \`dark\` class on an ancestor, and on the docs root itself. */
.dark .docs-root,
.dark.docs-root {
${indent(block(source, '.dark'))}
}
`,
);
console.log(`gen-theme: wrote ${OUT}`);
